@startuml
class Player {
- _pion : Pawn
- _PileCarte : Card[6]
- _age : Integer
+ <<Create>> Joueur()
+ getAge() : Integer

}
class Pawn{
- _posX : Integer
- _posY : Integer
+ <<Create>> Pawn()
+ move()
+ getPositionX() : Integer
+ getPositionY() : Integer
}

class Map{
}

class Tile{
- _estFixe: boolean
- _image: Image
- _x : Integer
- _y : Integer
+ <<Create>> Tile(estFixe : boolean, image String)
}
abstract Card{
- _background_path : String
- _image : Image
+ <<Create>> Card(_background_path : String)
+ isAccessible() : boolean
}
class Game{
}
@enduml